# ===================================================================
# Plan for Shocktube Phase 2: Hyperdiffusion & Convergence (Agnostic)
# ===================================================================
hpc:
  source_base_dir: '/scratch/project_200826/chau/chausims/sod_10_test_proj/quick_test_sod'
  run_base_dir: '/scratch/project_200826/chau/runs/shocktube_phase2'
  module_loads: |
    module load gcc/11.2.0 openmpi/4.1.2 openblas/0.3.18-omp csc-tools StdEnv hdf5/1.10.7-mpi
  sbatch:
    job_name: "shock_sweep_ph2"
    account: "project_200826"
    partition: "small"
    time: "01:00:00"
    nodes: 1
    ntasks: 1
    cpus_per_task: 1
    mail_user: "chau.c.tran@aalto.fi"
    mail_type: "END"

# --- Experiment Generation Parameters ---
base_experiment: 'shocktube_base'
output_prefix: 'shock'

# --- Configuration-Driven Naming and Logic ---
run_name_template: "{{ output_prefix }}_res{{ nxgrid }}_C{{ hyper_C | fs_safe }}_{{ branch.name }}"

derived_parameters:
  u_max: 200.0
  dx: "1.0 / nxgrid"
  nu_hyper3: "hyper_C * (dx**3 * u_max)" # Corrected from dx**5 based on typical scaling
  chi_hyper3: "nu_hyper3"

# --- Parameter Sweeps ---
parameter_sweeps:
  - type: product
    variable: nxgrid
    values: [400, 800, 1600]
  - type: product
    variable: hyper_C
    values: [0.2, 1.0, 5.0]

# --- Branches ---
branches:
  - name: "massfix_hyper"
    settings:
      run_in.yaml:
        density_run_pars: { lmassdiff_fix: true }
  - name: "nomassfix_hyper"
    settings:
      run_in.yaml:
        density_run_pars: { lmassdiff_fix: false }