# ===================================================================
# Plan for the Shocktube Phase 2 Parameter Sweep
# ===================================================================
# This file defines the hyperdiffusion parameter sweep.
# Phase 2 focuses on finding the best nu_hyper3 and chi_hyper3 values
# while keeping shock parameters fixed at their optimal values from Phase 1.
---

# --- HPC Execution Parameters ---
hpc:
  source_base_dir: '/scratch/project_2008296/chau/chausims/generated_sims_project_group/sod_10_test_proj/quick_test_sod'
  run_base_dir: '/scratch/project_2008296/chau/runs/shocktube_phase2'

  module_loads: |
    module load gcc/11.2.0
    module load openmpi/4.1.2
    module load openblas/0.3.18-omp
    module load csc-tools
    module load StdEnv
    module load hdf5/1.10.7-mpi

  sbatch:
    job_name: "shock_sweep_ph2"
    account: "project_2008296"
    partition: "small"
    time: "00:30:00"
    nodes: 1
    ntasks: 1
    cpus_per_task: 1
    mail_user: "chau.c.tran@aalto.fi"
    mail_type: "END"

# --- Post-Processing Automation (Optional) ---
auto_check: true
auto_postprocessing: true

# --- Error Analysis Configuration ---
# Using L1 error metric for consistency with Phase 1
error_analysis:
  metrics: ['l1']
  combine_in_videos: true

# --- Experiment Generation Parameters ---
base_experiment: 'shocktube_base'
output_prefix: 'res400_hyper3'

# Naming scheme for Phase 2 runs
run_name_template: "{{ output_prefix }}_nu{{ nu_hyper3 | fs_safe }}_chi{{ chi_hyper3 | fs_safe }}_{{ branch.name }}"

# --- Global Modifications ---
# These modifications apply to ALL runs in this phase
modifications:
  run_in.yaml:
    # Fix shock parameters at their optimal values from Phase 1
    density_run_pars: { diffrho_shock: 1.0 }
    viscosity_run_pars: { nu_shock: 1.0 }
    entropy_run_pars: { chi_shock: 1.0 }

# --- Parameter Sweeps ---
# Sweep hyperdiffusion parameters while keeping them equal (nu_hyper3 = chi_hyper3)
parameter_sweeps:
  - type: linked
    variables: [nu_hyper3, chi_hyper3]
    values: [9.0e-15, 9.0e-14, 9.0e-13, 9.0e-12]

# --- Branches ---
# Test with lgamma_is_1 = false as specified
branches:
  - name: "gamma_default"
    settings:
      run_in.yaml:
        density_run_pars: { lgamma_is_1: false }
