# config/shocktube_base/in/run_in.yaml
format: namelist
data:
  run_pars:
    bcx: ['a', 's', 's', 's', 's', 's']
    cdt: 0.005
    cdtv: 0.005
    cdts: 0.005
    cvsid: "9a97ecc83"
    dsnap: 1.0e-4
    dtmin: 1.0e-12
    dvid: 0.02
    isave: 10000
    tmax: 0.001
    it1: 1000
    itorder: 3
    lpencil_check: false
    nt: 1200000

  density_run_pars:
    diffrho_shock: 1.0
    idiff: 'shock'
    lmassdiff_fix: true

  # Include the hyper params in the base, as they exist in the working reference
  entropy_run_pars:
    chi_shock: 1.0
    iheatcond: ['shock']

  viscosity_run_pars:
    ivisc: ['nu-shock']
    nu_shock: 1.0
  
  eos_run_pars: {}
  hydro_run_pars: {}
