# config/shocktube_base/in/run_in.yaml
format: namelist
data:
  run_pars:
    bcx: ['a', 's', 's', 's', 's', 's']
    cdt: 0.1
    # ... (all other run_pars)
    nt: 6000

  density_run_pars:
    diffrho_shock: 1.0
    idiff: 'shock'
    lmassdiff_fix: true

  entropy_run_pars:
    chi_hyper3: 9.0e-14
    chi_shock: 1.0
    iheatcond: ['shock', 'hyper3']

  viscosity_run_pars:
    ivisc: ['nu-shock', 'hyper3-nu-const']
    nu_hyper3: 3.0e-12
    nu_shock: 1.0
  
  # Empty namelists
  eos_run_pars: {}
  hydro_run_pars: {}