# Plan for the shocktube_phase1 parameter sweep
---
# --- HPC Execution Parameters ---
hpc:
  # CORRECTED: The base directory for the source simulation on the HPC.
  source_base_dir: '/scratch/project_2008296/chau/chausims/generated_sims_project_group/sod_10_test_proj/quick_test_sod'
  
  # CORRECTED: The destination directory for the generated runs on the HPC.
  run_base_dir: '/scratch/project_2008296/chau/runs/shocktube_phase1'

  # SLURM SBATCH parameters for the array job submission script.
  sbatch:
    job_name: "shock_sweep_ph1"
    account: "project_2008296"
    partition: "medium"
    time: "01:00:00"
    nodes: 1
    ntasks_per_node: 1
    mail_user: "chau.c.tran@aalto.fi"
    mail_type: "END"

# --- Experiment Generation Parameters ---
base_experiment: 'shocktube_base'
output_prefix: 'res400'

# ... (sweep_parameters and branches remain the same as the corrected version) ...
sweep_parameters:
  nu_shock: [0.1, 0.5, 1.0, 5.0]
  chi_shock: [0.1, 0.5, 1.0, 5.0]
  diffrho_shock: [0.1, 0.5, 1.0, 5.0]

branches:
  - name: "massfix_isothermal"
    settings:
      run_in.yaml:
        density_run_pars: { lmassdiff_fix: true }
      start_in.yaml:
        density_init_pars: { gamma: 1.0 }

  - name: "massfix_adiabatic"
    settings:
      run_in.yaml:
        density_run_pars: { lmassdiff_fix: true }
      start_in.yaml:
        density_init_pars: { gamma: 1.666667 }

  - name: "nomassfix_adiabatic"
    settings:
      run_in.yaml:
        density_run_pars: { lmassdiff_fix: false }
      start_in.yaml:
        density_init_pars: { gamma: 1.666667 }