# config/shocktube_phase1/plan/sweep.yaml
---
hpc:
  source_base_dir: '/scratch/project_2008296/chau/chausims/generated_sims_project_group/sod_10_test_proj/quick_test_sod'
  run_base_dir: '/scratch/project_2008296/chau/runs/shocktube_phase1'
  sbatch:
    # ... (sbatch parameters are correct)

base_experiment: 'shocktube_base'
output_prefix: 'res400_nohyper'

# Modifications to apply to the base configuration for the ENTIRE suite.
modifications:
  run_in.yaml:
    # This section removes the hyper-parameters from the base config
    viscosity_run_pars:
      nu_hyper3: null # 'null' deletes the key
    entropy_run_pars:
      chi_hyper3: null # 'null' deletes the key
    # This section updates the lists now that hyper is removed
    viscosity_run_pars_update:
      ivisc: ['nu-shock']
    entropy_run_pars_update:
      iheatcond: ['shock']

# Defines the parameter sweep (this is correct)
sweep_parameters:
  nu_shock: [0.1, 0.5, 1.0, 5.0]
  chi_shock: [0.1, 0.5, 1.0, 5.0]
  diffrho_shock: [0.1, 0.5, 1.0, 5.0]

# Defines the branches. NOTE: No 'gamma' or 'l_gamma_is_1' here.
branches:
  - name: "massfix"
    settings:
      run_in.yaml:
        density_run_pars:
          lmassdiff_fix: true

  - name: "nomassfix"
    settings:
      run_in.yaml:
        density_run_pars:
          lmassdiff_fix: false